### ISSUE TITLE
Ruby 1.9 support.

### ISSUE THREAD

**Issue by dpc** [defunkt/github-gem#3] opened 2009-06-10 18:51 UTC
<pre>
$ github
/var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/github/extensions.rb:11: warning: undefining `object_id' may cause serious problem
/var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/github.rb:149:in `module_eval': /var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/commands/commands.rb:40: syntax error, unexpected ')' (SyntaxError)
  helper.tracking.sort { |(a,),(b,)| a == helper.origin ? -...
                              ^
/var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/commands/commands.rb:40: syntax error, unexpected '|', expecting '='
...per.tracking.sort { |(a,),(b,)| a == helper.origin ? -1 : b ...
...                               ^
/var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/commands/commands.rb:40: syntax error, unexpected '}', expecting keyword_end
...rigin ? 1 : a.to_s <=> b.to_s }.each do |(name,user_or_url)|
...                               ^
    from /var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/github.rb:149:in `load'
    from /var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/github.rb:66:in `block in activate'
    from /var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/github.rb:65:in `each'
    from /var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/lib/github.rb:65:in `activate'
    from /var/lib/gems/1.9.0/gems/defunkt-github-0.3.4/bin/github:8:in `<top (required)>'
    from /var/lib/gems/1.9.0/bin/github:19:in `load'
    from /var/lib/gems/1.9.0/bin/github:19:in `<main>'
</pre>

**Comment by rkh** [comment] 2009-07-01 18:18
Anybody working on that one?

**Comment by Daenyth** [comment] 2009-10-02 13:29
I'd really like to see this fixed soon... Arch has moved to ruby 1.9, which means that this app no longer works without installing 1.8 alongside, which is rather ugly.

**Comment by wfarr** [comment] 2009-11-11 16:33
I've made fixes in my fork which work for me. Whether or not they maintain complete 1.8.6 and 1.8.7 compatibility, I'm not sure.

**Comment by Daenyth** [comment] 2009-11-12 14:07
Would those be the 5 commits from your 1.9.x branch? Probably for packaging purposes I'll format-patch those commits and apply them onto the main branch for now.

**Comment by wfarr** [comment] 2009-11-12 15:10
Yes. And I've confirmed the test-suite runs 100% on 1.8.7.

**Comment by Daenyth** [comment] 2009-11-12 16:25
Awesome. I'll look into it.

**Comment by sunaku** [comment] 2009-11-18 06:10
Here's an update on Ruby 1.9 status with the github 0.4.0 gem:  simply running the `github` command fails with `ruby 1.9.1p243 (2009-07-16 revision 24175) [i686-linux]`.

```
% github
/usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/github/extensions.rb:11: warning: undefining `object_id' may cause serious problem
/usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/github.rb:151:in `module_eval': /usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/commands/helpers.rb:5: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
  when %r|^git://github\.com/([^/]+/[^/]+)$|: $1.split('/')
                                             ^
/usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/commands/helpers.rb:6: syntax error, unexpected keyword_when, expecting keyword_end
  when %r|^(?:ssh://)?(?:git@)?gith...
      ^
/usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/commands/helpers.rb:6: syntax error, unexpected ':', expecting keyword_end
...@)?github\.com:([^/]+/[^/]+)$|: $1.split('/')
...                               ^
/usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/commands/helpers.rb:8: syntax error, unexpected keyword_end, expecting $end
  from /usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/github.rb:151:in `load'
  from /usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/github.rb:68:in `block in activate'
  from /usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/github.rb:67:in `each'
  from /usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/lib/github.rb:67:in `activate'
  from /usr/lib/ruby/gems/1.9.1/gems/github-0.4.0/bin/github:8:in `<top (required)>'
  from /usr/bin/github:19:in `load'
  from /usr/bin/github:19:in `<main>'
```

**Comment by wfarr** [comment] 2009-11-18 06:18
This is a known issue which I've fixed in my branch. It's because ruby1.9 no longer supports the `when cond: blah` syntax. You need to use newlines or `when cond then blah`.

**Comment by sunaku** [comment] 2009-11-18 06:32
Thanks for the update.  I will use your fork for now and I hope your changes are pulled into upstream soon. :-)

**Comment by bmaland** [comment] 2009-11-28 10:26
I'm using wfarr's fork as well, works fine on my Ruby 1.9.1p243 system. Seems safe to merge into mainline

**Comment by nobu** [comment] 2010-04-18 02:25
Regarding wfarr's fork, line 45 in lib/commands/commands.rb changed the semantics from the original.  It should be |(a,_),(b,_)| not |a,b|, I think.

**Comment by dolzenko** [comment] 2010-05-05 12:58
Ok, I just went and commented the block on line 45 and replaced `:` with newlines in `github-0.4.2/lib/commands/helpers.rb`. Things seem to be working so far :)

**Comment by docunext** [comment] 2010-05-21 22:44
I'd love to see the patch from wfarr's fork integrated into mainline as well, thanks!

**Comment by kristianmandrup** [comment] 2010-06-17 06:31
I have a working 1.9 fork here: http://github.com/kristianmandrup/github-gem
I've also added some other patches found in the network, such as a fix for $ gh network
http://github.com/dominikh/github-gem/commit/3756a55c840ddbaef60d596250372e51faf07afc

http://github.com/snowblink/github-gem/commit/3726b5e0f1f1129e41550f753e1d2207a3f5063c

Also converted it into a jewel, for use with jeweler.

**Comment by bronson** [comment] 2010-08-17 02:52
Dammit, forgot github had an issue tracker.  Iidn't look here before spending my time porting it to 1.9.2.

Here's my tree: http://github.com/bronson/github-gem  Tested and works great on 1.8.6 and 1.9.2rc2.

Could one of the maintainers PLEASE pull one of the 1.9.2 fix trees?  The fixes are small and well understood.  I'm bummed I duplicated other peoples' work.

**Comment by kristianmandrup** [comment] 2010-08-17 09:13
Great! In my fork, I later noticed that the "create repository" command didn't work. Anyone experienced this or has a fix for it?

**Comment by bronson** [comment] 2010-08-24 03:26
Hi Kristian.  I don't experience that.  In my fork create repository seems to work perfectly under 1.8.6 and 1.9.2.  Tell me if you can find a way to break it.

**Comment by millisami** [comment] 2010-11-30 09:33
Still its not pulled in to the master repo.!! Same error with me.

**Comment by kristianmandrup** [comment] 2010-11-30 10:39
Hi bronson and millisami,

Here are my results after a few minutes investigation:

<pre>
kristian-mandrups-macbook-pro:_clones kristianconsult$ github create blip
/Users/kristianconsult/.rvm/gems/ruby-1.9.2-p0/gems/github-0.4.5/lib/github/command.rb:131:in `run': undefined method `any?' for "":String (NoMethodError)
</pre>


So I added a String extension

<pre>
class String 
  def any?
    !empty?
  end
end 
</pre>


Now I get another error :(

<pre>
$ github create blip
ERROR: kristianmandrup/blip doesn't exist yet. Did you enter it correctly?
fatal: The remote end hung up unexpectedly
</pre>


Why, WTF? Am I missing something here? I thought it would create the repo without expecting it to be present there already!?

I pushed my gem with the fix so you have the option to check it out or work on it if you like.

**Comment by mdarby** [comment] 2010-12-24 04:37
A year? Really?

**Comment by keithpitt** [comment] 2011-01-15 12:57
I've got a pull request which fixes all the Ruby 1.9 problems:

https://github.com/defunkt/github-gem/pull/36

**Comment by drnic** [comment] 2011-01-30 23:31
I think these are all applied now.

**Comment by sunaku** [comment] 2011-01-31 06:25
Hurray!  Thanks for following through on this long awaited request :)

**Closed as completed** 2011-01-31 07:31 UTC
Labels: ruby19
