### ISSUE TITLE
github gem doesn't install on 1.9

### ISSUE THREAD

**Issue by ajsharp** [defunkt/github-gem#48] opened 2011-03-09 00:20 UTC
on ruby 1.9.2, running `gem install github -v 0.6.0` gives the following error:

ERROR:  Error installing github:
        text-hyphen requires Ruby version < 1.9.

**Comment by briancollins** [comment] 2011-03-09 00:21
+1

**Comment by dmarkow** [comment] 2011-03-22 19:58
Looks like the problem is actually in the recent 1.0.2 release of text-hyphen. Doing a `gem install text-hyphen -v 1.0.0` first lets you install the github gem.

http://www.ruby-forum.com/topic/1049486#980481

**Comment by drnic** [comment] 2011-04-03 14:19
Fixed in 0.6.1

**Closed as completed by drnic** 2011-04-03 14:19 UTC
Labels: ruby19

**Comment by ajsharp** [comment] 2011-04-03 16:46
:thumbsup:
