### ISSUE TITLE
json_pure error - A JSON text must at least contain two octets! (JSON::ParserError)

### ISSUE THREAD

**Issue by kristianmandrup** [defunkt/github-gem#69] opened 2011-08-08 17:22 UTC
<pre>
Kristian-Mandrups-MacBook-Air:database_cleaner kmandrup$ gh pull stanislaw master --merge
/Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/json_pure-1.5.3/lib/json/common.rb:148:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/json_pure-1.5.3/lib/json/common.rb:148:in `new'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/json_pure-1.5.3/lib/json/common.rb:148:in `parse'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/lib/commands/helpers.rb:406:in `block in load'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/lib/commands/helpers.rb:345:in `block in load'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/lib/commands/helpers.rb:326:in `block in load'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/lib/commands/commands.rb:118:in `block in load'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/lib/github/command.rb:25:in `call'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/lib/github.rb:76:in `invoke'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/lib/github.rb:70:in `activate'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/gems/github-0.6.2/bin/gh:8:in `<top (required)>'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/bin/gh:19:in `load'
    from /Users/kmandrup/.rvm/gems/ruby-1.9.2-p290/bin/gh:19:in `<main>'</pre>
</pre>

**Comment by pcreux** [comment] 2011-08-11 02:11
+1

**Comment by xnzacc** [comment] 2011-08-29 12:29
+1

**Comment by xnzacc** [comment] 2011-08-29 12:58
My issue was that my github config in ~/.gitconfig was corrupt. Re-config by:

$ git config --global github.user "your-github-username"
$ git config --global github.token "your-github-token"

Same as https://github.com/defunkt/github-gem/issues/39#issuecomment-971246

**Comment by jergason** [comment] 2011-09-15 14:51
I just updated my `~/.gitconfig`, and I am still having the same issue.

**Comment by pcreux** [comment] 2011-09-16 09:14
I think that my credentials were just invalid. (when you change your
password, your api credentials change as well). It's working fine now.

φ

On Thu, Sep 15, 2011 at 16:51, Jamison Dance
reply@reply.github.com
wrote:

**Comment by paulp** [comment] 2011-12-01 16:11
As I note in the duplicate issue: "I had this very frustrating issue for a long time (is spewing a stack trace really the best error message available?) and finally fixed it by removing GITHUB_USER and GITHUB_TOKEN from my gitconfig and hardcoding my actual credentials."

**Comment by bilke** [comment] 2012-01-16 10:09
+1

**Comment by jjb** [comment] 2012-01-18 23:48
@kristianmandrup wanna close this issue since it's a duplicate of #39?

**Comment by evan** [comment] 2012-02-25 19:37
The github gem will drop an invalid empty "network cache" file at .git/network-cache if the credentials are busted. Remove it, fix your credentials, then try.

**Closed as completed** 2012-02-28 08:44 UTC
