### ISSUE TITLE
github gem requires json gem, but doesn't depend on it

### ISSUE THREAD

**Issue by indirect** [defunkt/github-gem#11] opened 2009-12-05 04:30 UTC
The github gem should depend on the json gem, so that `gem install github` will install it.

I installed the github gem, but when I ran `gh`, I got this:

```
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- json (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/local/Cellar/Gems/1.8/gems/github-0.4.0/bin/../lib/github.rb:9
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/local/Cellar/Gems/1.8/gems/github-0.4.0/bin/gh:6
    from /usr/local/bin/gh:19:in `load'
    from /usr/local/bin/gh:19
```

**Comment by pnutus** [comment] 2010-01-25 16:58
This is a dupe of [issue 10](http://github.com/defunkt/github-gem/issues#issue/10).

**Comment by indirect** [comment] 2010-01-25 17:00
Huh, weird. I definitely didn't see issue 10 at the time. Thanks.

**Comment by drnic** [comment] 2010-04-28 02:07
Fixed now.

**Closed as completed by drnic** 2010-04-28 02:07 UTC
