### ISSUE TITLE
Network list JSON parsing bug

### ISSUE THREAD

**Issue by wfarr** [defunkt/github-gem#41] opened 2011-01-30 22:39 UTC
After installing the shiny, new 0.6.0 github-gem, I went into a repository and ran some network list action.

```
wfarr at macbook using ree-1.8.7-2010.02 in moonshine/ on master  
› gh network list
/Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/json-1.4.6/lib/json/common.rb:146:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/json-1.4.6/lib/json/common.rb:146:in `new'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/json-1.4.6/lib/json/common.rb:146:in `parse'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/lib/commands/helpers.rb:381:in `cache_data'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/lib/commands/helpers.rb:336:in `get_network_data'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/lib/commands/helpers.rb:326:in `network_members'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/lib/commands/network.rb:23:in `command'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/bin/../lib/github/command.rb:25:in `send'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/bin/../lib/github/command.rb:25:in `call'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/bin/../lib/github.rb:76:in `invoke'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/bin/../lib/github.rb:70:in `activate'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/gems/github-0.6.0/bin/gh:8
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/bin/gh:19:in `load'
from /Users/wfarr/.rvm/gems/ree-1.8.7-2010.02/bin/gh:19
```

Fearing the worst, I bravely ran some more `network list` action!

```
wfarr at macbook using ree-1.8.7-2010.02 in moonshine/ on master  
› gh network

You have to provide a command :

    web [user]     - opens your web browser to the network graph page for this
                     project, or for the graph page for [user] if provided

    list           - shows the projects in your network that have commits
                     that you have not pulled in yet, and branch names

    fetch          - adds all projects in your network as remotes and fetches
                     any objects from them that you don't have yet

    commits        - will show you a list of all commits in your network that
                     you have not ignored or have not merged or cherry-picked.
                     This will automatically fetch objects you don't have yet.

      --project (user/branch)  - only show projects that match string
      --author (email)         - only show projects that match string
      --after (date)           - only show commits after date
      --before (date)          - only show commits before date
      --shas                   - only print shas (can pipe through 'github ignore')
      --applies                - filter to patches that still apply cleanly
      --sort                   - how to sort the commits (date, branch, author)

wfarr at macbook using ree-1.8.7-2010.02 in moonshine/ on master  
› gh network list
railsmachine
rmatei
andrewroth
titanous
Empact
ches
technicalpickles
jnewland
edavis10
benstein
orangethunder
mcommons
digitalscientists
skalnik
nberger
griffordson
bkaney
davidakachaos
sborsje
nragaz
tecodan
jgarber
crankharder
mkrisher
JasonKing
benhutton
jarinudom
john-griffin
eric
juhat
dreamcat4
```

Suddenly all was well!

Still trying to reproduce, but no luck. Looks like it might've been a one-off.

**Comment by drnic** [comment] 2011-01-31 00:23
Duplicate of #39

**Closed as completed by drnic** 2011-01-31 00:23 UTC
