### ISSUE TITLE
gh fails: core dumped

### ISSUE THREAD

**Issue by badboy** [defunkt/github-gem#17] opened 2010-02-11 11:15 UTC
github command fails with "core dumped"

system: Arch Liunx, 64bit
    $ ruby -v
    ruby 1.9.1p378 (2010-01-10 revision 26273) [x86_64-linux]
output: http://files.expertura.de/pub/github_core_dump.txt

if you need the coredump-file, I can upload it, too.

**Comment by grempe** [comment] 2010-03-25 17:39
+1 I am seeing this issue as well with Ruby 1.9.1 installed via rvm.

$ ruby -v
ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-darwin10.2.0]

**Comment by dominikh** [comment] 2010-04-02 19:35
I personally fixed that issue in http://github.com/dominikh/github-gem/commit/3756a55c840ddbaef60d596250372e51faf07afc

**Comment by cartazio** [comment] 2010-07-21 00:17
when will that be merged with the official version?

**Comment by drnic** [comment] 2011-04-03 13:51
Ok, so it took a year until I looked at this ticket; but dominikh's commit is gone. Was it already merged via other pull requests?

**Comment by dominikh** [comment] 2011-04-03 21:03
Yeah, sorry for that.

I, however, checked the current version and cannot reproduce the segfault anymore.

Furthermore I believe that commit e93939511753067a076e47c81bc7648e6a12300c fixed the issue, because it was the `|(a,),(b,)|` part that Ruby choked on, which Keith Pitt fixed in order to add support for 1.9.2

**Closed as completed** 2014-10-28 13:45 UTC
Labels: ruby19
